DataTables/Buttons

- js/dataTables.buttons.js
Currently if you have a data table which has no columns (edge use case I know) and you try to do something like export to csv, nothing appears to happen because of a division by 0. This allows the file to create at least the user isn't wondering why nothing is happening.
> prevent RangeError when no columns present

- js/buttons.html5.js
When the datatable contains non-string data (i.e. numbers) currently this line fails when trying to call "replace". I've just added a string addition to ensure it's a string at this point.
> Prevent error when exporting to HTML5 CSV when data contains numbers

- js/dataTables.buttons.js
Hi, I've found a bug in the current version 1.0.3 of the Buttons extension. Among the various button selectors, the selector by name (using the `:name` suffix) does not work. Another user [posted this bug and a possible solution](https://www.datatables.net/forums/discussion/30257/button-selector-by-name-doesn-t-work-in-buttons-fix-included) to the free community support forum in September, but it has been overlooked since then, obviously. That's why I'm making this pull request now hoping that it will be integrated soon because I can confirm that the other user's proposed code change fixes the problem.
> Fix button selector by name

- js/buttons.html5.js
Older versions of IE do not allow a focus to be set to a hidden element.  This creates an issue with the copy function in older IE browsers where if a datatable is embedded in a modal or other element which overlays the entire page, the textarea in the hiddenDiv cannot receive the focus, so it's contents cannot be copied.  
By changing where we attach the hidden div so we are attaching it to the table container, we are ensuring that we can use the copy feature in older browsers.
> Attach hiddenDiv for copyHtml5 to table container instead of body

- js/buttons.colVis.js
The issue: if I've added a button after init using `dt.button().add(index, obj)`, and there is a column hidden using colVis when I attempt to destroy the DatatTable instance via `dt.destroy()`, I get a Javascript error.
Example of error: https://jsfiddle.net/jpobley/wgofyfxx/15/
This error does not occur if a button has not been added after init using the method explained above. It is also important to note that I'm attempting to destroy the instance only using `dt.destroy()`, not the instance _and_ the table node using `dt.destroy(true)`. This error does not occur when passing `true`.
Example with fix from this PR: https://jsfiddle.net/jpobley/wgofyfxx/14/
The issue is the when the DT instance is destroyed, it makes all invisible columns visible, which attempts to activate a column's …
> FIX: Check if the DataTable is destroying before activating the column

- js/dataTables.buttons.js
Hi!
I recently had a problem with the removal of html code when exporting table contents with html5 buttons.
For some reason the regular expression used to detect html tags fails when an attribute contains linebreaks (which seems to be legit when using multiline tooltips - https://html.spec.whatwg.org/multipage/dom.html#the-title-attribute).
Please take a look at https://jsfiddle.net/x5tdnt7k/3/ and check the generated csv output.
I've adopted the regular expression which seems to resolve the issue.
However, I haven't found out yet why exactly this change solves the problem (all the regular expression documentations I checked indicate that both versions of the regex should behave identically).
In case you want to merge this pull request:
I acknowledge that this contribution is offered …
> Ensure that html stripping works with html code containing linebreaks

- js/buttons.html5.js
Details: https://datatables.net/forums/discussion/35471/buttons-is-there-a-size-limit-for-copy
TL;DR: `document.execCommand('copy')` will fail silently if the data being copied to the clipboard is too large (we're talking a couple hundred KB in some cases), unless you check its boolean return value to determine success.
> Bug Fix: Detect copy success, fall back to CTRL+C on failure

- js/buttons.html5.js
Currently there are 50 styles available to style cells. This request adds 6 styles for cell content alignment.
I'm proposing the following styles:
50 - Left aligned text
51 - Centered text
52 - Right aligned text
53 - Justified text
54 - Text rotated 90°
55 - Wrapped text (Useful when cells contain the <br/> tag converted to \r\n
Example:
```js
customize: function(xlsx){
//Make column headers
var sheet = xlsx.xl.worksheets['sheet1.xml'];
$('row:first c',sheet).attr('s','42');
// Apply alignment style to column, except the header    
$('row c[r^="B"]:gt(0)',sheet).attr('s','53');
}
```
> Add additional styles for exporting to excel

- js/buttons.html5.js
Hi everyone!
I've found a problem while exporting to excel and have a blank string or null values.
When I open the xlsx file, it creates this tag:
```
<c t="inlineStr" r="D2">
<is>
<t/>
</is>
</c>
```
This D2 cell is blank. But when I try to use the COUNTBLANK function on excel, this cell is counted and it shouldn't. It's like this D2 cell has some value..
And when I delete the cell on excel and open the xml again, this whole tag is deleted. So, the excel only identifies blank/null cell when it does not have this cell hierarchy.
> Fix: null, undefined and blank cell in excel export

- js/buttons.flash.js
- js/buttons.html5.js
There are a couple of issues with the <(.*?) xmlns=""(.*?)> expression.  The first is that it will actually capture ' xmlns=""' inside the text of an XML element.  This can be seen here: https://regex101.com/r/OlyTWe/2
The second issue is that in Chrome, this string doesn't exist unless it was in the table data.  This means that the first capture group captures the entire XML string character by character.  This causes a serious hit to performance.
I have rewritten the expression so that it should in almost all cases only match the string when it is an attribute inside of a tag.  This also reduces the amount of text captured in the first group and markedly improves performance when exporting thousands of rows in Chrome.  An example of the new expression working on the same string from the …
> Modify regex to be correct and more efficient.

- js/dataTables.buttons.js
Fixes an error if the DataTables "dom" has the property for Buttons but there are no buttons config defined.
> Fix an error when there is no buttons config

- js/buttons.html5.js
There was a 'config' parameter missing on the exportInfo() function that prevented csv files to be exported with the correct filename.
> Fix: csvHtml5 exported file was missing the filename

- js/dataTables.buttons.js
When the space beneath the button is not sufficient for the menu, it will now open to the top of the button.
To try out, position the colvis button the bottom row of a table.
> Make buttons menu (e.g. colvis menu) position above the button when neccessary

- js/buttons.colVis.js
​I've encountered an issue with formatting column names in show/hide button dropdown menu.
When I separated words with 'br' tag in column header, there was no space between them in dropdown menu.
Here is the additional regexp that solves this.
> added new regexp for formatting header names in dropdown menu

- js/buttons.html5.js
When working with Buttons, I noticed that the merged cells count was being concatenated instead of added.
I checked out my coding changes, and this is what I got:
> Add vs concatenate merged cells count

- docs/button/collection.xml
- js/buttons.print.js
- js/dataTables.buttons.js
Hi Allan, 
A property to force a collection to "drop up". If not set or set to false, it falls back to the default behaviour. Like Bootstrap's "dropup" class.
NB: When I set the buttons to show in table footer, a collection button was always dropping down, even when it would have been visually better to drop up (for instance, half of the collection was going overflow and required the user to scroll to click on a button). Maybe it's the way the overflows are calculated that needs to be improved... (?)
Don't know if it's a valuable PR for you... 
Thanks
> Collection dropup property

- js/dataTables.buttons.js
Discussion: https://datatables.net/forums/discussion/51832/feature-to-prevent-blur-on-button-click/
Done in the simplest way possible, with preserving the current default behaviour. 
(If there's guidelines of how invalidish input should be handled i.e. if clickBlurs is not a boolean, let me know so I can modify the PR to incorporate the system required).
> Add clickBlurs parameter to prevent blurring on specific buttons

- js/buttons.bootstrap4.js
This will make a line break on overflowing buttons.
https://datatables.net/forums/discussion/57149/bootstrap-4-table-buttons-small-device
> added class flex-wrap to button container

- js/buttons.html5.js
Automatically sets the cell format to 'date' when exporting a date (yyyy-mm-dd) to Excel, using the existing `var _excelSpecials`
Credits not to me, I just saw this discussion, and wonder why it has not been PR yet ?!?!
https://datatables.net/forums/discussion/50616/what-is-the-correct-format-to-export-dates-with-html5-to-excel#Comment_134583
> Formating dates to excel

- js/dataTables.buttons.js
jQuery event shorthands are marked as deprecated and removed in recent jQuery versions.
> jQuery.fn.blur() event shorthand is deprecated
> Replace deprecated jQuery event shorthand

- docs/option/buttons.buttons.split.xml
- examples/split/bootstrap.xml
- examples/split/bootstrap4.xml
- examples/split/bootstrap5.xml
- examples/split/bulma.xml
- examples/split/dataTables.xml
- examples/split/foundation.xml
- examples/split/jqueryui.xml
- examples/split/semanticui.xml
Hey there,
Browsing a bit through the documentation I came across a 404 via https://datatables.net/reference/option/butttons.buttons.split.
Current example (first link): https://datatables.net/extensions/buttons/examples/split/dataTables.html
I'm not that familiar with how the entire documentation is built up, but I hope that this PR can simply fix it.
BR,
Marco
> Fix: cross reference of `buttons.buttons.split`

- types/types.d.ts
According to documentation [docs](https://datatables.net/reference/button/spacer) spacer should have "style"
Fix error: TS2322: Type '{ extend: string; style: string; text: string; }' is not assignable to type 'ButtonSettings'.   Object literal may only specify known properties, and 'style' does not exist in type 'ButtonSettings'.
> Add spacer button style definition

- js/buttons.html5.js
This fixes errors/warnings with some spreadsheet software, including Gnumeric.
> Fix: Quote Excel sheet name in case it contains spaces

- docs/api/buttons.exportData().xml
It looks like this documentation update was missed in the revert at https://github.com/DataTables/Buttons/commit/afb6b2ab3eb7ae0f573eb5a3e0eeb9257ce478fd.
> Docs: Correct default orthogonal value for exportData()

- js/buttons.html5.js
In export to clipboard (copy).
When `document.execCommand('copy')` is unsuccessful.
A prompt with instructions to copy is displayed.
If we cancel the prompt by using the ESC key, the callback function `cb` is called.
But if we cancel the prompt by clicking on it, the callback function `cb` is not called.
`cb`should be called in all cancel scenarios.
This PR fixes it.
> Fix missing call to cb in "copy" when clicking to cancel prompt

- js/buttons.print.js
This avoids issues with Content Security Policy (CSP) restrictions that prevent us from injecting inline styles or relying on script-based styling.
By cloning and appending the stylesheets, we preserve the look and feel of the printed table without triggering CSP violations. Also added a fix to convert relative URLs to absolute ones for linked stylesheets—helps avoid broken styles in the new window.
Should be a solid step toward making print/export more reliable across browsers and environments with strict CSP settings.
> Fix: Avoid innerHTML in print button to comply with CSP
